# Generated by Django 5.1.1 on 2024-09-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_form_country_form_phone_form_surname_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
