# Generated by Django 5.1.1 on 2024-09-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_form_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='event_date',
            field=models.DateField(),
        ),
    ]
