# Generated by Django 5.1.1 on 2024-09-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_form_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='country_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='country_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='event_date_en',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='event_date_ru',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='phone_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='phone_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='surname_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='surname_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
