# Generated by Django 5.1.1 on 2024-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_form_country_en_form_country_ru_form_event_date_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
