# Generated by Django 5.1.1 on 2024-09-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_form_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='event_date_en',
        ),
        migrations.RemoveField(
            model_name='form',
            name='event_date_ru',
        ),
        migrations.RemoveField(
            model_name='form',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='form',
            name='phone_ru',
        ),
    ]
